name = "Fifty"
license = "Creative Commons Attribution 3.0"
licenselink = "https://github.com/CasualGaming/fifty/blob/master/LICENSE.md"
description = "A simple personal or corporate website theme."
homepage = "https://github.com/CasualGaming/fifty"
tags = ["personal", "company", "google analytics"]
features = []
min_version = "0.51"

[author]
  name = "Casual Gaming"
  homepage = "https://casualgaming.no"

[original]
  author = "Marcus Virginia"
  name = "Forty"
  homepage = "https://github.com/MarcusVirg/forty"